<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "simple_instagram"
 *
 * Auto generated by Extension Builder 2018-10-13
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Simple Instagram',
    'description' => 'Shows a Instagram feed with a given access Token. Only installation via composer is supported!',
    'category' => 'plugin',
    'author' => 'Benjamin Riezler',
    'author_email' => 'b.riezler@pixel-ink.de',
    'state' => 'stable',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.3',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.1-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
